run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosec
    - gocyclo
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - bodyclose
    - wrapcheck

linters-settings:
  gocyclo:
    min-complexity: 15
  errcheck:
    check-type-assertions: true
  revive:
    rules:
      - name: exported
        disabled: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0
